import { ASSETS, INDICATORS, POSTURE_FIXTURE, VULNERABILITIES, type SecurityEvent } from './fixtures';
import { Risk, RiskDistribution } from './Evidence';
import AnimatedMetric from './AnimatedMetric';

export default function Dashboard({ events, reviewedIds, onInspect, onReview }: { events: SecurityEvent[]; reviewedIds: string[]; onInspect: (id: string) => void; onReview: () => void }) {
  const critical = events.filter(event => event.risk === 'Critical');
  const frequency = Array.from(new Set(events.map(event => event.time.slice(0, 5)))).sort().map(minute => ({ minute, count: events.filter(event => event.time.startsWith(minute)).length }));
  const pending = events.filter(event => !reviewedIds.includes(event.id));
  return <div className="rk-overview">
    <section className="rk-posture" aria-label="Fictional security posture"><div><span className="rk-label">Security posture · baseline fixture</span><strong>{POSTURE_FIXTURE.status}</strong><p>Coverage unverified · No security assurance</p></div><div><span className="rk-label">Fixture risk score</span><strong>{POSTURE_FIXTURE.riskScore}<small> / {POSTURE_FIXTURE.maximumScore}</small></strong><p>Authored example, not a live score</p></div><div><span className="rk-label">Prepared investigation context</span><p>{VULNERABILITIES.length} illustrative findings · {INDICATORS.length} intelligence records</p><p>{VULNERABILITIES.filter(item => item.severity === 'Critical').length} Critical finding · No CVEs asserted</p></div><details><summary>How to read this baseline</summary><p>{POSTURE_FIXTURE.basis}</p></details></section>
    <div className="rk-overview-cards"><div><span className="rk-label">Fixture events</span><AnimatedMetric value={events.length} /><span>{ASSETS.length} reserved-domain assets</span></div><div><span className="rk-label">Critical queue</span><AnimatedMetric value={critical.length} /><span>Scenario labels; validate with owner</span></div><div><span className="rk-label">Recommendations awaiting review</span><AnimatedMetric value={pending.length} /><span>{reviewedIds.length} reviewed locally</span></div></div>
    <div className="rk-two-column"><RiskDistribution events={events} /><section className="rk-subpanel"><h4>Event frequency</h4><p className="rk-footnote">Fixture window · 2026-01-15 UTC</p>{frequency.map(item => <div className="rk-frequency" key={item.minute}><time>{item.minute}</time><span className="rk-bar-track"><span className="rk-bar rk-bar--low" style={{ width: `${item.count / Math.max(...frequency.map(bucket => bucket.count)) * 100}%` }} /></span><span>{item.count} events</span></div>)}</section></div>
    <div className="rk-two-column"><section className="rk-subpanel"><h4>Selected critical queue</h4>{critical.length ? critical.slice(0, 2).map(event => <div className="rk-queue-item" key={event.id}><Risk level={event.risk} /><button className="rk-event-link" type="button" onClick={() => onInspect(event.id)}>{event.title}</button><p>{event.target} · {event.status}</p></div>) : <p className="rk-footnote">No Critical scenario events in this session.</p>}</section><section className="rk-subpanel"><h4>Recent timeline</h4>{[...events].sort((a, b) => b.time.localeCompare(a.time)).slice(0, 3).map(event => <div className="rk-queue-item" key={event.id}><time className="rk-mono">{event.time} UTC</time><button className="rk-event-link" type="button" onClick={() => onInspect(event.id)}>{event.title}</button></div>)}</section></div>
    <section className="rk-subpanel"><h4>Next review</h4>{pending.slice(0, 1).map(event => <p key={event.id} className="rk-footnote">{event.id}: {event.recommendation}</p>)}{!pending.length && <p className="rk-footnote">All session recommendations reviewed locally.</p>}<button type="button" className="rk-text-button" onClick={onReview}>Review recommendations</button></section>
  </div>;
}
