import { useState } from 'react';
import { ArrowRight } from 'lucide-react';
import { RouteLink, SectionHeader } from '../components/ui';
import type { PageProps } from '../types/site';
import { PageTabs } from './pageTools';
import './pages.css';

const methodology = [
  { id: 'discover', number: '01', label: 'Discover', title: 'Agree the environment before reviewing it.', description: 'Start with the organization’s objectives, system ownership, and available inventory. Resolve unclear boundaries and record exclusions before discovery informs assessment.', input: 'Business objectives, asset owners, and known inventory', output: 'An agreed scope, ownership map, and evidence gaps', review: 'Who can authorize access, and which systems are explicitly excluded?', lane: 'ATTACK / AUTHORIZED ASSESSMENT' },
  { id: 'assess', number: '02', label: 'Assess', title: 'Evaluate only what has been authorized.', description: 'Define permissions, test windows, stop conditions, and rules of engagement. Review approved applications, configurations, and defensive visibility using agreed methods.', input: 'Written authorization, approved assets, and test constraints', output: 'Documented observations and safely collected evidence', review: 'Are testing boundaries, escalation contacts, and stop conditions clear?', lane: 'ATTACK / AUTHORIZED ASSESSMENT' },
  { id: 'understand', number: '03', label: 'Understand', title: 'Distinguish evidence from hypothesis.', description: 'Connect observations to system behavior and available threat context. Validate suspected findings, consider alternative explanations, and keep collection limitations visible.', input: 'Observations, event sources, and technical context', output: 'Verified findings, hypotheses, and remaining uncertainty', review: 'What supports the conclusion, and what still needs verification?', lane: 'ATTACK → DEFENCE / ANALYST REVIEW' },
  { id: 'prioritize', number: '04', label: 'Prioritize', title: 'Turn findings into owned decisions.', description: 'Review exposure alongside business criticality, practical remediation options, and operational impact. Agree what needs attention first and who is responsible for it.', input: 'Findings, asset criticality, and business constraints', output: 'A prioritized action plan with owners and verification criteria', review: 'Which action is justified by the evidence and business context?', lane: 'DEFENCE / DECISION OWNERSHIP' },
  { id: 'defend', number: '05', label: 'Defend', title: 'Make approved changes and verify them.', description: 'Translate priorities into scoped hardening, access-control, or monitoring work. System owners approve changes and reviewers check outcomes against the agreed finding.', input: 'Prioritized work and change permissions', output: 'Recorded defensive changes and verification evidence', review: 'Did the change address the finding without unacceptable operational impact?', lane: 'DEFENCE / APPROVED CHANGE' },
  { id: 'respond', number: '06', label: 'Respond', title: 'Coordinate containment, evidence, and recovery.', description: 'Use agreed escalation paths when incident context demands action. Balance containment decisions with evidence preservation, available access, and business continuity requirements.', input: 'Incident context, authorized playbooks, and decision-makers', output: 'An incident record, recovery checks, and outstanding actions', review: 'Who owns the next decision, and how will recovery be verified?', lane: 'SECURE / COORDINATED RESPONSE' },
  { id: 'improve', number: '07', label: 'Improve', title: 'Feed the evidence back into the next review.', description: 'Review observed coverage and process gaps. Update inventories, procedures, and defensive controls, then plan authorized retesting as the environment changes.', input: 'Verification results, incident lessons, and operational feedback', output: 'Updated controls and a scoped next-review plan', review: 'What changed in the environment, and what should be assessed next?', lane: 'SECURE → DISCOVER / CONTINUOUS REVIEW' },
] as const;

export default function ApproachPage({ setActivePage }: PageProps) {
  const [stage, setStage] = useState<typeof methodology[number]['id']>('discover');
  const current = methodology.find((item) => item.id === stage) ?? methodology[0];
  return <div className="chx-pages pg-approach"><div className="cyber-container">
    <header className="pg-hero"><div className="pg-eyebrow">Our approach</div><h1>ATTACK. DEFENCE. SECURE.</h1><p className="pg-lead">Understand exposure through authorized assessment. Turn evidence into defensive decisions. Verify the outcome and improve the next review.</p><p className="pg-note"><strong>Authorization is the starting condition.</strong> The methodology describes scoped professional work; it does not authorize testing. Active assessment requires explicit permission, exclusions, and rules of engagement.</p></header>
    <section aria-labelledby="methodology-heading"><SectionHeader number="01" eyebrow="Connected methodology" title="A working loop, not an isolated test." description="Select a stage to trace how its input becomes the next stage’s evidence. Arrow keys, Home, and End move between stages." /><h2 id="methodology-heading" className="pg-sr-only">Assessment and defense methodology</h2>
      <div className="pg-methodology"><div className="pg-methodology-lanes" aria-hidden="true"><span>Attack · authorized assessment</span><span>Defence · owned decisions</span><span>Secure · verify & improve</span></div><PageTabs id="methodology" label="Connected methodology stages" items={methodology} value={stage} onChange={setStage} className="pg-methodology-tabs" /><p className="pg-loop-caption">Discover → Assess → Understand → Prioritize → Defend → Respond → Improve ↺ Return to discovery as the environment changes.</p></div>
      <section className="pg-panel pg-methodology-detail" role="tabpanel" tabIndex={0} id={`methodology-panel-${stage}`} aria-labelledby={`methodology-tab-${stage}`}><div className="pg-eyebrow">{current.lane}</div><div className="pg-stage-detail"><div><h2>{current.title}</h2><p>{current.description}</p></div><aside className="pg-note"><h3>The review question</h3><p>{current.review}</p></aside></div><div className="pg-handoff"><div><span className="pg-label">Input</span><p>{current.input}</p></div><ArrowRight aria-hidden="true" /><div><span className="pg-label">Working output → next stage</span><p>{current.output}</p></div></div></section>
    </section>
    <section className="pg-section pg-grid-two" aria-label="Working agreements"><div><div className="pg-eyebrow">Before an engagement</div><h2>Agree how the work will be judged.</h2><p className="pg-lead">Useful assessment work connects technical findings to an agreed operational outcome.</p></div><ol className="pg-editorial-list"><li><strong>Scope & authority</strong><p>Approved systems, asset owners, exclusions, test windows, and emergency stop contacts.</p></li><li><strong>Evidence & decisions</strong><p>Collection boundaries, review ownership, impact context, and documented limitations.</p></li><li><strong>Remediation & verification</strong><p>Achievable actions, responsible owners, change approval, and retest criteria.</p></li></ol></section>
    <section className="pg-cta" aria-label="Scope a security engagement"><div><h2>Start with the decision you need to make.</h2><p>Choose a service discipline or discuss an authorized scope with the team.</p></div><div className="pg-actions"><RouteLink page="services" onNavigate={setActivePage} className="btn-cyber-outline">Explore services</RouteLink><RouteLink page="licensing" onNavigate={setActivePage} className="btn-cyber-primary">Discuss your scope <ArrowRight size={16} aria-hidden="true" /></RouteLink></div></section>
  </div></div>;
}
