import { ArrowRight } from 'lucide-react';
import { Badge, RouteLink, SectionHeader } from '../components/ui';
import type { PageProps } from '../types/site';
import './pages.css';

export default function ProductsPage({ setActivePage }: PageProps) {
  return <div className="chx-pages pg-products"><div className="cyber-container">
    <header className="pg-hero"><div className="pg-eyebrow">Product portfolio</div><h1>Rakshak AI.<br />The flagship direction.</h1><p className="pg-lead">A security workflow concept centered on asset context, signal review, and evidence-led investigation. Explore the interactive demonstration and discuss requirements for a potential deployment.</p></header>
    <section className="pg-product-feature" aria-labelledby="rakshak-portfolio-title">
      <div className="pg-panel"><div className="pg-status-row"><Badge>PRODUCTION STATUS · UNCONFIRMED</Badge><Badge>AVAILABLE · INTERACTIVE DEMO</Badge></div><h2 id="rakshak-portfolio-title">Rakshak AI</h2><p>The demonstrated flagship illustrates how analysts could connect an environment overview with signals, investigation context, and review priorities. The website demo uses fictional data and local interactions.</p><p className="pg-note"><strong>Availability:</strong> “Available” refers only to the interactive website demo. Commercial availability, production capabilities, deployment options, integrations, and licensing are subject to confirmation.</p><div className="pg-actions"><RouteLink page="rakshak" onNavigate={setActivePage} className="btn-cyber-primary">Explore the Rakshak demo <ArrowRight size={16} aria-hidden="true" /></RouteLink><RouteLink page="licensing" onNavigate={setActivePage} className="btn-cyber-outline">Discuss platform requirements</RouteLink></div></div>
      <aside className="pg-facts" aria-label="Portfolio status"><dl><div><dt>Named product</dt><dd>Rakshak AI</dd></div><div><dt>Website demonstration</dt><dd>Interactive · Fictional fixtures</dd></div><div><dt>Production availability</dt><dd>Not confirmed</dd></div><div><dt>Evaluation next step</dt><dd>Requirements and feasibility discussion</dd></div></dl></aside>
    </section>
    <section className="pg-section" aria-label="What the demonstration illustrates"><SectionHeader number="01" eyebrow="Demonstrated workflow" title="Explore the decision, not a performance claim." description="The demo is a way to evaluate the workflow idea. It is not connected to live customer systems." /><div className="pg-grid"><article className="pg-card"><h3>Environment context</h3><p>Inspect sample assets and exposure context to frame the analyst’s review.</p></article><article className="pg-card"><h3>Signals & investigation</h3><p>Review fictional event patterns and their relationship to investigation priorities.</p></article><article className="pg-card"><h3>Human review</h3><p>Consider what evidence and approvals are needed before a real operational decision.</p></article></div><RouteLink page="threatlab" onNavigate={setActivePage} className="pg-card-link">Play a scripted investigation in Threat Lab <ArrowRight size={16} aria-hidden="true" /></RouteLink></section>
    <section className="pg-section" id="roadmap" aria-label="Illustrative development intentions"><SectionHeader number="02" eyebrow="Development direction" title="Questions that shape the next iteration." description="Illustrative product intentions for discussion, not a committed roadmap, release schedule, or promise of functionality." /><ol className="pg-roadmap"><li><span className="pg-card-number">01 / Validate the workflow</span><h3>Does the analyst have the right context?</h3><p>Use demo feedback to understand which asset, event, and evidence views help a reviewer reach a better-supported decision.</p></li><li><span className="pg-card-number">02 / Establish feasibility</span><h3>What would a real environment require?</h3><p>Explore data-source quality, access boundaries, integration needs, deployment responsibilities, and operating constraints before defining an implementation scope.</p></li><li><span className="pg-card-number">03 / Define readiness</span><h3>What must be verified before evaluation?</h3><p>Agree acceptance criteria, limitations, governance, support expectations, and commercial terms. Any future evaluation or release requires separate confirmation.</p></li></ol></section>
    <section className="pg-cta" aria-label="Product inquiry"><div><h2>Bring your workflow requirements.</h2><p>Start with the data you have, the decisions you need to support, and the constraints of your environment.</p></div><RouteLink page="licensing" onNavigate={setActivePage} className="btn-cyber-primary">Prepare a product inquiry</RouteLink></section>
  </div></div>;
}
