import { ArrowRight } from 'lucide-react';
import { Badge, RouteLink, SectionHeader } from '../components/ui';
import type { PageProps } from '../types/site';
import './pages.css';

export default function ResponsibleDisclosurePage({ setActivePage }: PageProps) {
  return <div className="chx-pages pg-disclosure"><div className="cyber-container">
    <header className="pg-hero"><div className="pg-eyebrow">Responsible disclosure</div><h1>Report responsibly.<br />Verify the channel first.</h1><p className="pg-lead">These published guidelines explain how to request a verified reporting route and what a useful report should contain once that route is established.</p><Badge>REPORTING CHANNEL NOT CONFIGURED</Badge></header>
    <section className="pg-disclosure-alert" aria-labelledby="disclosure-channel-title"><h2 id="disclosure-channel-title">Dedicated disclosure channel not configured.</h2><p><strong>Do not submit sensitive vulnerability evidence through general enquiry.</strong> No dedicated security email or secure submission endpoint has been confirmed for this website.</p><p>Use the contact page only to prepare a non-sensitive request for a verified disclosure channel. If contact delivery is not configured, the page produces a local draft and does not send it.</p><RouteLink page="licensing" onNavigate={setActivePage} className="btn-cyber-primary">Request a verified channel — no secrets <ArrowRight size={16} aria-hidden="true" /></RouteLink></section>
    <div className="pg-notice-layout"><nav className="pg-notice-nav" aria-label="Disclosure sections"><a href="#disclosure-scope">Scope</a><a href="#disclosure-report">How to report</a><a href="#disclosure-information">Information to include</a><a href="#disclosure-next">Next steps</a><a href="#disclosure-safe-harbor">Safe harbor status</a><a href="#disclosure-contact">Contact channel</a></nav><div className="pg-notice-body">
      <section id="disclosure-scope"><h2>Scope & authorization</h2><p>A formal vulnerability disclosure program, approved target list, and testing rules have not been confirmed. A website being publicly accessible does not grant testing permission. Third-party systems, customer environments, and infrastructure are not authorized targets under these guidelines.</p><p>For a concern observed without active testing, first request a verified channel. Any proposed testing requires separate written authorization from the relevant system owner, an agreed scope, and stop conditions.</p></section>
      <section id="disclosure-report"><h2>How to report</h2><ol className="pg-list"><li>Prepare a non-sensitive request for the team’s verified security reporting channel.</li><li>Confirm the recipient, secure transfer method, and reporting instructions before sharing evidence.</li><li>Send only the minimum evidence needed through that verified route. Keep credentials, personal information, and customer data out of general enquiry.</li></ol><p>Do not continue testing, access other users’ data, disrupt services, or attempt persistence while awaiting a response.</p></section>
      <section id="disclosure-information"><h2>Information for a verified report</h2><p>Once a secure route is agreed, a useful report can include:</p><ul className="pg-list"><li>The affected asset and why you believe it is within the owner’s control.</li><li>A concise description of the issue, observed impact, and limitations.</li><li>Minimal reproduction context from already authorized activity or passive observation.</li><li>Redacted evidence and relevant observation times.</li><li>A preferred reply route and any handling constraints.</li></ul><p>Do not create additional impact to demonstrate severity. Ask the owner how sensitive artifacts should be handled.</p></section>
      <section id="disclosure-next"><h2>What happens next</h2><p>The owner must confirm channel access, scope, handling instructions, and a review process. Acknowledgment targets, remediation timelines, rewards, and coordinated publication arrangements are not established here.</p><p>Request those expectations directly through the verified channel. The website does not represent a bounty program or guarantee a response or fix.</p></section>
      <section id="disclosure-safe-harbor"><h2>Safe harbor status</h2><p><strong>These guidelines do not grant permission to test and do not provide a safe harbor promise.</strong> A formal safe harbor commitment requires explicit owner approval and an approved program with defined boundaries.</p><p>No immunity, legal protection, waiver, or authorization for third-party systems is offered by this notice. Agree any assessment permissions separately before acting.</p></section>
      <section id="disclosure-contact"><h2>Contact channel</h2><p>The general enquiry page is suitable only for asking how to contact the security owner without disclosing vulnerability details. Check its delivery status; a local downloaded draft is not a submitted report.</p><RouteLink page="licensing" onNavigate={setActivePage} className="pg-card-link">Prepare a channel-verification request <ArrowRight size={16} aria-hidden="true" /></RouteLink></section>
    </div></div>
    <section className="pg-section" aria-label="Disclosure notice status"><SectionHeader eyebrow="Owner review required" title="A verified route comes before sensitive evidence." description="The organization must approve a dedicated channel, testing boundaries, report handling, and any formal disclosure commitments before a complete program can be published." /></section>
  </div></div>;
}
